// Code generated by counterfeiter. DO NOT EDIT.
package healthv1fake

import (
	"context"
	"sync"

	healthv1 "github.com/connect-sdk/health-api/proto/grpc/health/v1"
)

type FakeHealthServiceClient struct {
	CheckStub        func(context.Context, *healthv1.HealthCheckRequest) (*healthv1.HealthCheckResponse, error)
	checkMutex       sync.RWMutex
	checkArgsForCall []struct {
		arg1 context.Context
		arg2 *healthv1.HealthCheckRequest
	}
	checkReturns struct {
		result1 *healthv1.HealthCheckResponse
		result2 error
	}
	checkReturnsOnCall map[int]struct {
		result1 *healthv1.HealthCheckResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHealthServiceClient) Check(arg1 context.Context, arg2 *healthv1.HealthCheckRequest) (*healthv1.HealthCheckResponse, error) {
	fake.checkMutex.Lock()
	ret, specificReturn := fake.checkReturnsOnCall[len(fake.checkArgsForCall)]
	fake.checkArgsForCall = append(fake.checkArgsForCall, struct {
		arg1 context.Context
		arg2 *healthv1.HealthCheckRequest
	}{arg1, arg2})
	stub := fake.CheckStub
	fakeReturns := fake.checkReturns
	fake.recordInvocation("Check", []interface{}{arg1, arg2})
	fake.checkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHealthServiceClient) CheckCallCount() int {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	return len(fake.checkArgsForCall)
}

func (fake *FakeHealthServiceClient) CheckCalls(stub func(context.Context, *healthv1.HealthCheckRequest) (*healthv1.HealthCheckResponse, error)) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = stub
}

func (fake *FakeHealthServiceClient) CheckArgsForCall(i int) (context.Context, *healthv1.HealthCheckRequest) {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	argsForCall := fake.checkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeHealthServiceClient) CheckReturns(result1 *healthv1.HealthCheckResponse, result2 error) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = nil
	fake.checkReturns = struct {
		result1 *healthv1.HealthCheckResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeHealthServiceClient) CheckReturnsOnCall(i int, result1 *healthv1.HealthCheckResponse, result2 error) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = nil
	if fake.checkReturnsOnCall == nil {
		fake.checkReturnsOnCall = make(map[int]struct {
			result1 *healthv1.HealthCheckResponse
			result2 error
		})
	}
	fake.checkReturnsOnCall[i] = struct {
		result1 *healthv1.HealthCheckResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeHealthServiceClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHealthServiceClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ healthv1.HealthServiceClient = new(FakeHealthServiceClient)
